import { StyleSheet } from "react-native";
import {normalize} from '../../../../utils/helpers';
import * as Constants  from '../../../../components/KoraText';
export default StyleSheet.create({
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'center',
    minHeight: 44,
    marginLeft: 16,
    marginTop: 10,
    marginBottom: 10,
    marginRight: 10,
    // padding: 20,
    backgroundColor: "#fff",
  },
  createGroupRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'center',
    minHeight: 44,
    marginLeft: 0,
    marginTop: 15,
    marginBottom: 0,
    marginRight: 10,
    // padding: 20,
    backgroundColor: "#fff",
  },
  createGroup1:{flex: 1},
  createGroup2:{paddingLeft: 5, paddingRight: 5},
  createGroup3:{
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#85B7FE',
    borderRadius: 22,
  },
  heading: {
    marginVertical: 15,
    marginHorizontal: 15,
    fontWeight: '400',
    fontSize: normalize(16),
    fontStyle: 'normal',
     fontFamily: Constants.fontFamily,
    lineHeight: normalize(16),
    color: '#202124',
  },
  buttonGrey: {
    margin: 10,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "grey",
  },
  forwardButton: {
    margin: 10,
    height: 35,
    minWidth: 90,
    justifyContent: "center",
  },
  cancelButton: {
    margin: 10,
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#696969",
    height: 35,
    minWidth: 90,
    justifyContent: "center",
  },
  pic: {
    // width: 60,
    // height: 60,
    // paddingLeft: 10,
  },
  nameContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingEnd:5,
    //  width: 330,
  },
  nameTxt: {
    marginLeft: 13,
    fontWeight: "400",
    color: "#202124",
    fontSize: normalize(15),
     width: '80%',
  },
  createGroupTxt: {
    marginLeft: 13,
    paddingBottom: 3,
    fontWeight: "400",
    color: "#202124",
    fontSize: normalize(15),
    width: '80%',
  },
  time: {
    fontWeight: "200",
    color: "#777",
    fontSize: normalize(13),
  },
  msgContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  msgTxt: {
    fontWeight: "normal",
    color: "#9AA0A6",
    fontFamily: 'Inter',
    fontSize: normalize(12),
    marginLeft: 15,
    marginRight: 5,
  },
  circle: {
    width: 15,
    height: 15,
    borderRadius: 15 / 2,
    backgroundColor: "#88D969",
    borderWidth: 2,
    borderRightColor: "#fff",
    borderLeftColor: "#fff",
    borderTopColor: "#fff",
    borderBottomColor: "#fff",
    position: "absolute",
    top: -5,
    right: 0,
  },
});
