import {StyleSheet} from 'react-native';
import {colors} from '../../theme/colors';
import * as Constants from '../KoraText';
import {normalize} from '../../utils/helpers';
export default StyleSheet.create({
  // text: {
  //   fontWeight: 'normal',
  //   fontSize: normalize(14),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  //   color: '#202124',
  //   lineHeight: normalize(19),
  // },
  tagContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    alignSelf: 'flex-end',
  },
  tagText: {
    marginLeft: 5,
    fontSize: normalize(14),
    lineHeight: normalize(16),
    color: '#5F6368',
  },
  mainContainer: {},
  userNameText: {
    fontWeight: 'bold',
    fontSize: normalize(12),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    marginRight: 5,
    color: '#202124',
    justifyContent: 'flex-start',
    textAlign: 'left',
  },
  searchHeader1: {
    // paddingHorizontal: 18,
    //paddingVertical: 11.125,
    //maxHeight: 54,

    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: 'grey',
    borderBottomWidth: 0.5,
    borderBottomColor: 'grey',
    backgroundColor: 'white',
  },
  searchHeader2: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#E5E8EC',
    height: 36,
    marginTop: 10,
    marginLeft: 20,
    marginRight: 20,
    marginBottom: 10,
  },
  timeStamp: {
    fontWeight: 'normal',
    fontSize: normalize(12),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#202124',
    opacity: 0.6,
  },
  text: {
    fontWeight: 'normal',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#202124',
    lineHeight: normalize(21),
  },
  senderText: {
    fontWeight: 'normal',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#202124',
    lineHeight: normalize(21),
  },
  urlSubText: {
    fontWeight: '400',
    fontSize: normalize(12),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#8B8888',
  },
  textTitle: {
    fontWeight: '400',
    fontSize: normalize(16),
    fontFamily: Constants.fontFamily,
    lineHeight: 18,
  },
  urlTextTitle: {
    fontWeight: '400',
    fontSize: normalize(14),
    fontFamily: Constants.fontFamily,
  },
  urlTextSubTitle: {
    fontWeight: '400',
    fontSize: normalize(12),
    fontFamily: Constants.fontFamily,
    lineHeight: 18,
  },
  textDesc: {
    fontWeight: '400',
    fontSize: normalize(14),
    fontFamily: Constants.fontFamily,
    lineHeight: 18,
    color: '#8B8888',
  },
  sendMessage: {
    backgroundColor: colors.blueLight,
    flex: 0,
    maxWidth: '80%',
    padding: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderTopRightRadius: 0,
    borderColor: 'rgba(95, 99, 104, 0.1)',
    borderBottomWidth: 1,
  },
  receiveMessage: {
    backgroundColor: '#EFF0F1',
    flex: 0,
    maxWidth: '80%',
    padding: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderBottomLeftRadius: 0,

    borderBottomColor: 'rgba(95, 99, 104, 0.1)',
    borderBottomWidth: 1,
  },
  //paddingTop5: {paddingTop: 5},
  doubleTick: {alignSelf: 'center'},
  doubleTick1: {alignSelf: 'center', marginLeft: 10},
  timeStamp1: {
    fontWeight: 'normal',
    fontSize: normalize(12),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#DD3646',
    opacity: 0.6,
    marginRight: 5,
  },
  textImageContainer: {flexDirection: 'row', alignItems: 'center'},
  // searchTextInputStyle: {
  //   fontWeight: '400',
  //   fontSize: normalize(16),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  //   width: '100%',
  // },
  textStyle1: {
    color: '#202124',
    fontWeight: '600',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },

  textStyle: {fontSize: normalize(18), fontWeight: '400', fontStyle: 'normal'},
  // cancelTextStyle: {
  //   color: '#0D6EFD',
  //   fontWeight: '500',
  //   fontSize: normalize(16),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  // },
  // modalTextStyle: {
  //   fontWeight: '400',
  //   fontSize: normalize(16),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  // },
  // fullNameTextStyle: {
  //   fontWeight: '500',
  //   fontSize: normalize(16),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  // },
  // tranceInfoTextStyle: {
  //   color: '#202124',
  //   flexShrink: 1,
  //   fontWeight: '600',
  //   fontSize: normalize(16),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  // },
  // timelineTextStyle: {
  //   fontWeight: '400',
  //   fontSize: normalize(12),
  //   fontStyle: 'normal',
  //   fontFamily: Constants.fontFamily,
  // },
  searchTextInputStyle: {
    fontWeight: '400',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    width: '100%',
    height: 36,
  },
  cancelTextStyle: {
    color: '#202124',
    fontWeight: '500',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  reminderHeaderStyle: {
    color: '#202124',
    fontWeight: '600',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    textAlign: 'center',
    paddingTop: 20,
    paddingBottom: 15,
  },
  modalTextStyle: {
    fontWeight: '500',
    fontSize: normalize(18),
    fontStyle: 'normal',
    color: '#202124',
    fontFamily: Constants.fontFamily,
  },

  fullNameTextStyle: {
    fontWeight: '500',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  fullNameTextStyleAvtar: {
    fontWeight: '600',
    fontSize: normalize(16),

    fontStyle: 'normal',
    color: 'white',
    fontFamily: Constants.fontFamily,
  },
  tranceInfoTextStyle: {
    color: '#202124',
    flexShrink: 1,
    fontWeight: '600',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    flex: 1,
  },
  focusedMessageTextStyle: {
    paddingTop: 4,
    paddingLeft: 10,
    fontWeight: '500',
    fontSize: normalize(15),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  timelineTextStyle: {
    fontWeight: '400',
    fontSize: normalize(14),
    lineHeight: normalize(17),
    color: '#202124',
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  timelineMain: {
    borderWidth: 1,
    borderColor: '#E4E5E7',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 30,
    backgroundColor: '#EFF0F1',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 0,
  },
  authorNameTextStyle: {
    fontWeight: 'bold',
    fontSize: normalize(12),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#202124',
  },
  fileNameTextStyle: {
    color: '#202124',
    lineHeight: 17,
    fontWeight: '400',
    fontSize: normalize(14),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  fileSizeTextStyle: {
    paddingRight: 4,
    color: '#5F6368',
    fontWeight: '400',
    fontSize: normalize(10),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  forwardedTextStyle: {
    color: '#202124',
    marginLeft: 5,
    fontWeight: '400',
    fontSize: normalize(12),
    fontStyle: 'italic',
    fontFamily: Constants.fontFamily,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  horizontal: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 5,
  },
  lineSeparator: {
    height: 1,
    width: '100%',
    backgroundColor: '#EFF0F1',
  },
  lineSeparatorMain: {
    flex: 1,
    paddingHorizontal: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
  },
  imageComponent: {
    flex: 1,
    width: '100%',
    height: null,
    // resizeMode: 'contain',
    // aspectRatio: 1,
  },

  stickyDate: {
    marginTop: 1,
    alignSelf: 'center',
    textAlign: 'center',
    height: 30,
    width: '100%',
    position: 'absolute',
    //justifyContent: 'center',
    backgroundColor: '#ffffff00',
    top: 8,
    //borderRadius: 10,
    //marginBottom: 10,
  },
});
