require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# Override Firebase SDK Version
$FirebaseSDKVersion = '7.1.0'
$RNFirebaseAsStaticFramework = true

target 'KoraApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'
  pod 'WatermelonDB', :path => '../node_modules/@nozbe/watermelondb'

  # NOTE: Do not remove, needed to keep WatermelonDB compiling:
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'TextToSpeech', :path => '../node_modules/react-native-tts'

  pod 'react-native-create-thumbnail', :path => '../node_modules/react-native-create-thumbnail'

  
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  pod 'RNBootSplash', :path => '../node_modules/react-native-bootsplash'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  pod 'react-native-photo-view-ex', :path => '../node_modules/react-native-photo-view-ex'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-progress-bar-android', :path => '../node_modules/@react-native-community/progress-bar-android'

  pod 'react-native-progress-view', :path => '../node_modules/@react-native-community/progress-view'

  target 'KoraAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end

target 'KoraApp-tvOS' do
  # Pods for KoraApp-tvOS

  target 'KoraApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
