import {StyleSheet} from 'react-native';
import {normalize} from '../../utils/helpers';
import * as Constants from '../../components/KoraText';

export default StyleSheet.create({
  headerTopicName: {
    fontSize: normalize(18),
    fontWeight: 'bold',
    marginLeft: 10,
  },
  mainStyle1: {flex: 1, backgroundColor: 'white'},
  mainStyle2: {flex: 1, flexDirection: 'column', backgroundColor: 'white'},
  muteStyle1: {
    borderRadius: 4,
    flexDirection: 'row',
    paddingVertical: 16,
  },
  topicNameStyle: {flexShrink: 1, paddingRight: 10},
  text: {
    color: '#0D6EFD',
    fontSize: normalize(16),
    fontWeight: '500',
  },
  bottomUpModal1: {
    paddingLeft: 20,
    paddingBottom: 11,
    borderColor: '#9AA0A6',
    marginBottom: 9,
  },
  bottomUpModal2: {paddingVertical: 16},
  textStyle: {
    fontWeight: '500',
    fontSize: normalize(16),
    color: '#202124',
  },
  cancelTextStyle: {
    color: '#DD3646',
    fontWeight: '400',
    fontSize: normalize(16),
  },
  muteStyle: {
    color: '#202124',
    fontSize: normalize(16),
    fontWeight: '600',
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
  messageHeaderContainer: {
    padding: 18,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: 'grey',
    borderBottomWidth: 0.25,
    borderBottomColor: 'grey',
    height: 54,
    width: '85%',
    justifyContent: 'flex-start',
  },
  backButtonStyle: {paddingRight: 6},
  threadType: {flexDirection: 'row', alignItems: 'center', flexShrink: 1},
  mainStyle: {
    backgroundColor: 'white',
    paddingTop: 0,
  },
  optionsStyle1: {
    margin: 4,
    minHeight: 40,
    paddingHorizontal: 10,
    justifyContent: 'center',
    borderRadius: 5,
  },
  optionStyles2: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionStyles3: {
    marginRight: 10,
    minWidth: 30,
    marginLeft: 8,
    alignItems: 'center',
  },
  multiSelect1: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '15%',
    borderBottomWidth: 0.25,
    borderBottomColor: 'grey',
    justifyContent: 'center',
    height: 54,
  },
  multiSelect2: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '15%',
    justifyContent: 'center',
    height: 54,
  },
  multiSelect3: {paddingLeft: 10},
  messageHeaderOuterContainer: {
    marginRight: 5,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: 'grey',
    borderBottomWidth: 0.25,
    borderBottomColor: 'grey',
    justifyContent: 'space-between',
    height: 54,
  },
  headerContactName: {
    fontSize: normalize(18),
    fontWeight: 'bold',
    marginLeft: 10,
  },
  participantStyle: {
    width: '100%',
    flexShrink: 1,
    position: 'absolute',
    bottom: 0,
  },
  composeBarParent: {backgroundColor: 'white'},
  bottomUpModal3: {padding: 6},
  iconStyle: {
    width: 36,
    height: '100%',
    alignContent: 'center',
    marginStart: 8,

    alignItems: 'center',
    borderRadius: 5,
    justifyContent: 'center',
  },
  composerbar_container: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    backgroundColor: 'white',
    paddingLeft: 15,
    paddingRight: 15,
    minHeight: 50,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderColor: '#E6E7E9',
  },
  chatLoadingStyle: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    // opacity: 0.5,
    zIndex: 5,
    // backgroundColor: 'clear',
    justifyContent: 'center',
    alignItems: 'center',
  },
  send_btn_style: {
    padding: 7,
    marginStart: 12,
    width: 34,
    //marginVertical: -2.8,
    // paddingVertical: -2.8,
    justifyContent: 'center',
    alignItems: 'center',

    // marginTop: 0,
  },
  send_btn_container_style: {
    flexDirection: 'row',
    alignSelf: 'center',
    // justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    height: 50,
  },

  icon_Style: {marginStart: 10},
  buttons_container: {
    flexDirection: 'row',
   
    // justifyContent: 'space-between',
    alignItems: 'flex-end',
    backgroundColor: 'white',
    height: 50,
  },
  buttons_sub_container: {
    flexDirection: 'row',
    alignSelf: 'flex-end',
    // justifyContent: 'space-between',
    alignItems: 'flex-end',
    backgroundColor: 'white',
    height: 50,
  },
  sendViewStyle: {
    // height: '100%',
    //  backgroundColor: 'white',
    justifyContent: 'center',
    // marginStart: 10,
    alignItems: 'center',
    borderRadius: 5,
    alignSelf: 'center',
    marginStart: 16,
    padding: 8,
    width: 35,
  },
});
