import {StyleSheet} from 'react-native';
import {normalize} from '../../utils/helpers';
import * as Constants from '../../components/KoraText';

export default StyleSheet.create({
  editTextStyle: {
    fontWeight: '500',
    fontSize: normalize(14),
    lineHeight: normalize(25),
    color: '#FFFFFF',
  },

  editSectionMain: {
    backgroundColor: '#202124',
    paddingHorizontal: 15,
    paddingVertical: 4.5,
    alignItems: 'center',
    flexDirection: 'row',
  },
  cancelColor: {color: '#8f9091'},

  iconStyle: {
    width: 36,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    alignSelf: 'center',
  },

  iconStyleAudio: {
    marginStart: 15,
    alignItems: 'center',
    borderRadius: 5,
    justifyContent: 'center',
  },

  ViewGroupTimer: {
    alignItems: 'center',
    flexDirection: 'row',
    alignContent: 'center',
    flexShrink: 1,
  },
  inputTextStyleTimer: {
    marginBottom: 1,
    marginLeft: 10,
    fontSize: normalize(14),
    fontWeight: '400',
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    borderBottomWidth: 0,
    borderBottomColor: 'white',
    color: '#DD3646',
    flex: 1,
    width: '100%',
  },
  inputTextStylePlay: {
    marginBottom: 1,
    marginLeft: 10,
    fontSize: normalize(14),
    fontWeight: '400',
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    borderBottomWidth: 0,
    borderBottomColor: 'white',
    color: '#0D6EFD',
    flex: 1,
    width: '100%',
  },
  inputTextStylePlay1: {borderRadius: 5},
  TouchableOpacityStyle: {
    // position: 'absolute',
    // alignItems: 'center',
    // justifyContent: 'center',
    // // bottom: 18,xx
    // borderRadius: 4,
  },

  FloatingButtonStyle: {
    // resizeMode: 'contain',
    // width: 35,
    // height: 35,
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: '#DD3646',
    // borderRadius: 4,
  },
  // FloatingButtonStyle1: {
  //   height: 36,
  //   flexDirection: 'column',
  // },
  FloatingButtonStyle2: {borderRadius: 4},
  ViewGroup: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    backgroundColor: 'white',
    backgroundColor: 'white',
  },
  borderDivStyle: {},
  sendStyle1: {},
  inputTextStyle: {
    backgroundColor: 'white',
    maxHeight: 128,
    textAlign: 'left',
    // minHeight: normalize(40),
    flex: 1,
    marginVertical:5,
    fontSize: normalize(16),
    lineHeight: normalize(20),
    fontWeight: 'normal',
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    borderBottomWidth: 0,
    paddingVertical: 0,
    
    paddingTop: 0,
    borderBottomColor: 'white',
  },
  inputTextStyle1: {
    flexDirection: 'row',
    alignSelf: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: 'white',
  },
  placeHolder: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
  },
  actionViewStyle: {
    marginEnd: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendViewStyle: {
    backgroundColor: '#0D6EFD',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    width: 28,
  },
  toolTipStyle1: {
    flexDirection: 'row',
    alignItems: 'center',
    alignContent: 'center',
  },
  toolTipStyle2: {
    color: '#FFFFFF',
    marginEnd: 10,
    fontWeight: '400',
    fontSize: normalize(16),

    fontStyle: 'normal',
    alignContent: 'center',
    fontFamily: Constants.fontFamily,
  },
  send_btn_container: {
    alignItems: 'center',
    justifyContent: 'center',
    marginStart: 7,
  },
  body: {
    padding: 0,
    backgroundColor: '#FFFFFF',
  },
  mainStyle: {
    flexDirection: 'column',
    backgroundColor: '#000000',
    margin: 1,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    width:"100%",
    elevation: 2,
  },
  listStyle: {maxHeight: 150, backgroundColor: '#fff'},
  box: {
    marginTop: 5,
    marginBottom: 5,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
  },
  box1: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    borderRadius: 22,
    marginLeft: 15,
  },
  box2: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  username: {
    fontFamily: Constants.fontFamily,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: normalize(14),

    color: '#292929',
    paddingLeft: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  emailAddress: {
    fontFamily: Constants.fontFamily,
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: normalize(12),
    marginTop: 2,
    color: '#5F6368',
    paddingLeft: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    alignSelf: 'flex-start',
  },
  iconContent: {
    backgroundColor: 'white',
    marginLeft: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
  },
  icon: {
    width: 40,
    height: 40,
  },
  checkBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignContent: 'center',
  },
  nameTextStyle: {
    fontWeight: '400',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#07377F',
  },
  nameTextStyle1: {
    fontWeight: '400',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: 'white',
  },
  typingStyle1: {flexDirection: 'row', padding: 5},
  typingStyle: {
    width: 30,
    height: 30,
    borderRadius: 30 / 2,
    marginRight: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  characterTextStyle: {
    fontWeight: '400',
    fontSize: normalize(16),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
    color: '#F8F9FA',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  recordingTextStyle: {
    color: '#FFF',
    marginEnd: 10,
    fontWeight: '400',
    fontSize: normalize(17),
    fontStyle: 'normal',
    fontFamily: Constants.fontFamily,
  },
});
